=== devwithu/CSharp200/VS2005/Project116/Project112/files/FundXml.xsd
<?xml version="1.0" encoding="euc-kr"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://itcampus.hankyung.com/fund.xsd" 
  elementFormDefault="qualified" 
  xmlns="http://itcampus.hankyung.com/fund.xsd">
  <xs:element name="kosdaq">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="stock">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="stock">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="stockname">
        </xs:element>
        <xs:element ref="stockprice">
        </xs:element>
        <xs:element ref="prevstockprice">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="stockname" type="xs:string">
  </xs:element>
  <xs:element name="stockprice" type="xs:integer">
  </xs:element>
  <xs:element name="prevstockprice" type="xs:integer">
  </xs:element>
</xs:schema>

=== devwithu/CSharp200/VS2008/Project116/Project116/Project116/FundXml.xml
<?xml version="1.0" encoding="euc-kr"?>
<kosdaq xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:schemaLocation="http://itcampus.hankyung.com/fund.xsd FundXml.xsd"
        xmlns="http://itcampus.hankyung.com/fund.xsd">
  <stock>
    <stockname>CJ</stockname>
    <stockprice>65400</stockprice>
    <prevstockprice>-1100</prevstockprice>
  </stock>
  <stock>
    <stockname>CJ인터넷</stockname>
    <stockprice>16200</stockprice>
    <prevstockprice>200</prevstockprice>
  </stock>
  <stock>
    <stockname>CJ홈쇼핑</stockname>
    <stockprice>64800</stockprice>
    <prevstockprice>-1800</prevstockprice>
  </stock>
  <stock>
    <stockname>GS</stockname>
    <stockprice>45000</stockprice>
    <prevstockprice>400</prevstockprice>
  </stock>
  <stock>
    <stockname>GS건설</stockname>
    <stockprice>120000</stockprice>
    <prevstockprice>-4500</prevstockprice>
  </stock>
  </kosdaq>
